@echo off
echo Setting up Movie API...

echo Creating virtual environment...
python -m venv .venv

echo Activating virtual environment...
call .venv\Scripts\activate

echo Installing dependencies...
pip install -r requirements.txt

echo Running migrations...
alembic upgrade head

echo Seeding database...
python -m app.etl.seed

echo Starting server...
uvicorn app.main:app --reload