"""create movie and review tables

Revision ID: f43c3d698720
Revises: 
Create Date: 2026-03-17 17:06:14.687540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43c3d698720'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('actors', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_actors'), 'movies', ['actors'], unique=False)
    op.create_index(op.f('ix_movies_age'), 'movies', ['age'], unique=False)
    op.create_index(op.f('ix_movies_authors'), 'movies', ['authors'], unique=False)
    op.create_index(op.f('ix_movies_director'), 'movies', ['director'], unique=False)
    op.create_index(op.f('ix_movies_genre'), 'movies', ['genre'], unique=False)
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_index(op.f('ix_movies_info'), 'movies', ['info'], unique=False)
    op.create_index(op.f('ix_movies_link'), 'movies', ['link'], unique=False)
    op.create_index(op.f('ix_movies_rating'), 'movies', ['rating'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_link', sa.String(), nullable=True),
    sa.Column('critic_name', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_link'], ['movies.link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_critic_name'), 'reviews', ['critic_name'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_movie_link'), 'reviews', ['movie_link'], unique=False)
    op.create_index(op.f('ix_reviews_review'), 'reviews', ['review'], unique=False)
    op.create_index(op.f('ix_reviews_score'), 'reviews', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_score'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_movie_link'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_critic_name'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_rating'), table_name='movies')
    op.drop_index(op.f('ix_movies_link'), table_name='movies')
    op.drop_index(op.f('ix_movies_info'), table_name='movies')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_genre'), table_name='movies')
    op.drop_index(op.f('ix_movies_director'), table_name='movies')
    op.drop_index(op.f('ix_movies_authors'), table_name='movies')
    op.drop_index(op.f('ix_movies_age'), table_name='movies')
    op.drop_index(op.f('ix_movies_actors'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
